name: New Keyboard Layout
description: Request a new keyboard layout, language, or a change to an existing layout
labels: ["Enhancement", "Keyboard Layout"]
title: "Keyboard Layout: "
type: feature
projects: ["futo-org/23"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening a keyboard layout request.

        The [futo-keyboard-layouts](https://github.com/futo-org/futo-keyboard-layouts) issue tracker is reserved for issues relating to keyboard layouts the FUTO Keyboard Android Application

        For discussion related to enhancements, please see the [FUTO Keyboard Zulip Channel](https://chat.futo.org/#narrow/stream/53-Keyboard) or the [FUTO Keyboard Discord](https://keyboard.futo.org/discord)

        Please open requests one at a time. If you have 3 separate feature requests/bugs, do not combine them into one issue, this makes it really difficult to track and understand them.

  - type: input
    id: language
    attributes:
      label: Language
      description: Which language is this layout for?
      placeholder: "Swedish"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the layout to be added/changed, you can include the layout itself in a codeblock and any special behavior such as long-press keys. If this is a standard layout in other mobile keyboards, please mention it here and attach a screenshot of the layout.
      placeholder: |
        ```
        q w e r t y u i o p
        a s d f g h j k l
        z x c v b n m
        ```

        long-press q should have letter č
    validations:
      required: true

  - type: textarea
    id: complexity
    attributes:
      label: Complexity
      description: Does this language or layout require any complex input logic (e.g. Pinyin input method, Hangul character combiner) that does not already exist in the existing keyboard layouts? If so, please link to any open-source libraries or code that you're aware of for input in this language that may serve as a useful reference.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Note:** If the submit button is disabled and you have filled out all required fields, please check that you did not forget a **Title** for the issue.
